/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica3;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author JoseRamon
 */
public class Practica3 extends javax.swing.JFrame {

    /**
     * Creates new form Practica3
     */
    final char PRIMERA_LETRA = 'A', ULTIMA_LETRA = 'P';
    final int VUELTAS_BTN1 = 4, VUELTAS_BTN2 = 16;
    Random generador = new Random();
    int rango = ULTIMA_LETRA - PRIMERA_LETRA;
        
    public Practica3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton1.setEnabled(false);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton2.setEnabled(false);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton3.setEnabled(false);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton4.setEnabled(false);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton5.setEnabled(false);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton6.setEnabled(false);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton7.setEnabled(false);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton8.setEnabled(false);

        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton9.setEnabled(false);
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton10.setEnabled(false);

        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton11.setEnabled(false);

        jToggleButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton12.setEnabled(false);

        jToggleButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton13.setEnabled(false);

        jToggleButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton14.setEnabled(false);

        jToggleButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton15.setEnabled(false);

        jToggleButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica3/imagenes/Z.png"))); // NOI18N
        jToggleButton16.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jToggleButton1.setEnabled(false);jToggleButton1.setSelected(false);
        jToggleButton2.setEnabled(false);jToggleButton2.setSelected(false);
        jToggleButton3.setEnabled(false);jToggleButton3.setSelected(false);
        jToggleButton4.setEnabled(false);jToggleButton4.setSelected(false);
        jToggleButton5.setEnabled(false);jToggleButton5.setSelected(false);
        jToggleButton6.setEnabled(false);jToggleButton6.setSelected(false);
        jToggleButton7.setEnabled(false);jToggleButton7.setSelected(false);
        jToggleButton8.setEnabled(false);jToggleButton8.setSelected(false);
        jToggleButton9.setEnabled(false);jToggleButton9.setSelected(false);
        jToggleButton10.setEnabled(false);jToggleButton10.setSelected(false);
        jToggleButton11.setEnabled(false);jToggleButton11.setSelected(false);
        jToggleButton12.setEnabled(false);jToggleButton12.setSelected(false);
        jToggleButton13.setEnabled(false);jToggleButton13.setSelected(false);
        jToggleButton14.setEnabled(false);jToggleButton14.setSelected(false);
        jToggleButton15.setEnabled(false);jToggleButton15.setSelected(false);
        jToggleButton16.setEnabled(false);jToggleButton16.setSelected(false);
        String letras = "", URL = "";

        for (int i = 0; i < VUELTAS_BTN1; i++)
            letras += (char) (PRIMERA_LETRA + generador.nextInt(rango + 1));
        for (int i = 0; i < letras.length(); i++) {
            URL = "/practica3/imagenes/" + letras.charAt(i) + ".png";
            try {
                switch (i) {
                    case 0: jLabel1.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 1: jLabel2.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 2: jLabel3.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 3: jLabel4.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                }
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jToggleButton1.setEnabled(true);
        jToggleButton2.setEnabled(true);
        jToggleButton3.setEnabled(true);
        jToggleButton4.setEnabled(true);
        jToggleButton5.setEnabled(true);
        jToggleButton6.setEnabled(true);
        jToggleButton7.setEnabled(true);
        jToggleButton8.setEnabled(true);
        jToggleButton9.setEnabled(true);
        jToggleButton10.setEnabled(true);
        jToggleButton11.setEnabled(true);
        jToggleButton12.setEnabled(true);
        jToggleButton13.setEnabled(true);
        jToggleButton14.setEnabled(true);
        jToggleButton15.setEnabled(true);
        jToggleButton16.setEnabled(true);
        
        String letras = "", URL = "";
        for (int i = 0; i < VUELTAS_BTN2; i++)
            letras += (char) (PRIMERA_LETRA + generador.nextInt(rango + 1));
        for (int i = 0; i < letras.length(); i++) {
            URL = "/practica3/imagenes/" + letras.charAt(i) + ".png";
            try {
                switch (i) {
                    case 0: jToggleButton1.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 1: jToggleButton2.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 2: jToggleButton3.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 3: jToggleButton4.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 4: jToggleButton5.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 5: jToggleButton6.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 6: jToggleButton7.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 7: jToggleButton8.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 8: jToggleButton9.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 9: jToggleButton10.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 10: jToggleButton11.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 11: jToggleButton12.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 12: jToggleButton13.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 13: jToggleButton14.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 14: jToggleButton15.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                    case 15: jToggleButton16.setIcon(new ImageIcon (ImageIO.read(getClass().getResource(URL))));break;
                }
            } catch (IOException ex) {
                Logger.getLogger(Practica3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
